//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Majestic
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cliente()
        {
            this.Pedido = new HashSet<Pedido>();
        }
        [Display(Name = "Código")]
        public int cod_cli { get; set; }
        [Display(Name = "RUC")]
        public string ruc_cli { get; set; }
        [Display(Name = "Nombre")]
        public string nom_cli { get; set; }
        [Display(Name = "Teléfono")]
        public string telf_cli { get; set; }
        [Display(Name = "Email")]
        public string email_cli { get; set; }
        [Display(Name = "Dirección")]
        public string dir_cli { get; set; }
        public int cod_dis { get; set; }
        [Display(Name = "Estado")]
        public bool est_cli { get; set; }
    
        public virtual Distrito Distrito { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pedido> Pedido { get; set; }
    }
}
