//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Majestic
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.Pedido_Producto = new HashSet<Pedido_Producto>();
        }

        [Display(Name = "Código")]
        public int cod_prod { get; set; }
        [Display(Name = "Nombre")]
        public string nom_prod { get; set; }
        [Display(Name = "Stock Max.")]
        public int stock_max_prod { get; set; }
        [Display(Name = "Stock Min.")]
        public int stock_min_prod { get; set; }
        [Display(Name = "Precio List.")]
        public decimal prec_list_prod { get; set; }
        [Display(Name = "Cap. Bat.")]
        public string cap_bat { get; set; }
        public int cod_cat { get; set; }
        public int cod_mar { get; set; }
        [Display(Name = "Estado")]
        public bool est_prod { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        public virtual Marca Marca { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pedido_Producto> Pedido_Producto { get; set; }
    }
}
